### ISSUE TITLE
Add PlantUML to setup script using brew

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-macos-setup#2]
As part of https://github.com/riboseinc/asciidoctor-iso/issues/138 we should also install PlantUML (and JRE) via Homebrew.

**Comment by opoudjis** [comment]
This seems to have been as simple as adding `brew "plantuml"` to the Brewfile. Java is already being install in the main script; I've moved `brew cask install java` before `brew bundle`, to ensure Java is already in place when plantuml is installed. Updated Readme.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
