### ISSUE TITLE
Travis is breaking on  metanorma-macos-setup

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-macos-setup#8]
https://travis-ci.org/metanorma/metanorma-standoc/jobs/589729715#L2415

````
/Users/travis/.travis/functions: line 553: 14601 Terminated: 15          travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/Formula/metanorma.rb ; fi" failed and exited with 1 during .
````

This seems to be happening within running of the macos initialisation script, and several initialisation steps seem compromised, including LaTeX.

**Comment by ronaldtse** [comment]
This repo has been deprecated by https://github.com/metanorma/homebrew-metanorma. Closing.
